use_frameworks!

platform :ios, '10.0'

#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#  end
#end

target 'PXxlogger_Example' do
  pod 'PXxlogger', :path => '../'

  target 'PXxlogger_Tests' do
    inherit! :search_paths

    
  end
end
